{% set name = "unicorn-binance-suite" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicorn-binance-suite-{{ version }}.tar.gz
  sha256: 55c4d57cb251d76f17cf06fd74d7d1ad22ec12e39948153a5448b4e20d1e06dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - unicorn-binance-local-depth-cache
    - unicorn-binance-rest-api
    - unicorn-binance-trailing-stop-loss
    - unicorn-binance-websocket-api
    - unicorn-fy

test:
  imports:
    - unicorn_binance_local_depth_cache
    - unicorn_binance_rest_api
    - unicorn_binance_trailing_stop_loss
    - unicorn_binance_websocket_api
    - unicorn_fy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-binance-suite.html
  summary: Suite of packages for creating automated trading systems with the Binance API.
  description: |
    The UNICORN Binance Suite is a Python Meta Package of unicorn-fy, 
    unicorn-binance-local-depth-cache, unicorn-binance-rest-api, unicorn-binance-trailing-stop-loss and unicorn-binance-websocket-api.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-suite
  doc_url: https://unicorn-binance-suite.docs.lucit.tech

extra:
  recipe-maintainers:
    - oliver-zehentleitner
